# Generated by Django 4.1.7 on 2023-02-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_buy', '0003_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('ONCE', 'once'), ('FOREVER', 'forever'), ('REAPITING', 'repeating')], default='ONCE', max_length=10)),
                ('dis_id', models.CharField(max_length=255)),
                ('percent_off', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_buy.discount'),
        ),
    ]
