# Generated by Django 4.1.7 on 2023-02-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_buy', '0004_discount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stripe_buy.item'),
        ),
        migrations.AlterField(
            model_name='ordertoitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_buy.order'),
        ),
    ]
