# Generated by Django 4.1.7 on 2023-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_buy', '0005_alter_ordertoitem_item_alter_ordertoitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.CharField(choices=[('once', 'ONCE'), ('forever', 'FOREVER'), ('repeating', 'REAPITING')], default='ONCE', max_length=10),
        ),
    ]
