# Generated by Django 4.1.7 on 2023-02-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_buy', '0009_remove_order_tax_order_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='taxes',
        ),
    ]
